apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: bindings.service.projectriff.io
spec:
  group: service.projectriff.io
  names:
    kind: Binding
    plural: bindings
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            bindingSecret:
              description: SecretRef is the name of the Binding Secret that is created
                with the credentials
              type: string
            host:
              description: Host is the hostname or IP address for the service
              type: string
            hostKey:
              description: HostKey is the key for the host in the secret specified
                by SecretRef
              type: string
            passwordKey:
              description: PasswordKey is the key for the password in the secret specified
                by SecretRef
              type: string
            port:
              description: Port is the port used by the service
              type: string
            portKey:
              description: PortKey is the key for the port in the secret specified
                by SecretRef
              type: string
            secretRef:
              description: SecretRef is a reference to a Secret containing the credentials
              type: string
            uri:
              description: URI is the service URI that can be used to connect to the
                service
              type: string
            uriKey:
              description: URIKey is the key for the URI in the secret specified by
                SecretRef
              type: string
            username:
              description: Username is the username to use for connecting to the service
              type: string
            usernameKey:
              description: UsernameKey is the key for the username in the secret specified
                by SecretRef
              type: string
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
